---

- debug: msg="Configuring MultiChain Servers"

- name: Create Multichain chain1
  command: "{{ multichain_usr_dir }}/multichain-util create chain1" 
  args:
    creates: "~/.multichain/chain1/params.dat"

- name: Ensure we are always listening on network port 9239
  lineinfile: dest=~/.multichain/chain1/params.dat regexp=^default-network-port line="default-network-port = 9239"

- name: Ensure we are always listening on network port 9238
  lineinfile: dest=~/.multichain/chain1/params.dat regexp=^default-rpc-port line="default-rpc-port = 9238"

- name: Get service on port 9239
  shell: netstat -tunlp | grep ":9239 " | sed -e 's/.*\///'
  register: results

- name: Start MultiChain Server on Server 1
  command: "{{ multichain_usr_dir }}/multichaind chain1 -daemon" 
  when: results.stdout.find('multichaind') == -1

- name: Get service on port 9239 on Server 2
  shell: netstat -tunlp | grep ":9239 " | sed -e 's/.*\///'
  register: multichaind2_running
  delegate_to: 192.168.50.202

- name: Get MultiChain Server 2 address
  shell: "{{ multichain_usr_dir }}/multichaind chain1@192.168.50.201:9239 | grep grant | awk '{ print $4'} | uniq" 
  when: multichaind2_running.stdout.find('multichaind') == -1
  delegate_to: 192.168.50.202
  register: multichaind2_address
  ignore_errors: yes

- debug: var=multichaind2_address

- name: Add address to connect and transact
  command: "{{ multichain_usr_dir }}/multichain-cli chain1 grant {{ multichaind2_address.stdout }} connect,send,receive"
  when: multichaind2_running.stdout.find('multichaind') == -1
  register: results

- name: Start MultiChain Server on Server 2
  command: "{{ multichain_usr_dir }}/multichaind chain1@192.168.50.201:9239 -daemon" 
  when: multichaind2_running.stdout.find('multichaind') == -1
  delegate_to: 192.168.50.202