---

# - hosts: multichain
#   gather_facts: true
#   become: yes
#   roles:
#     - { role: darkedges.commonos }
#     - { role: darkedges.multichain }

- hosts: multichain-master
  gather_facts: true
  become: yes
  roles:
    # - { role: darkedges.multichain-explorer }
    #- { role: geerlingguy.nodejs }
    - { role: darkedges.bws }