---

- name: Install epel-release
  yum: name=epel-release

- name: Install pre-requisites packages
  yum: name={{ item }}
  with_items:
    - jq
    - net-tools

- include: multichain-install.yml
  when: inventory_hostname in groups['multichain']

- include: multichain-configure.yml
  when: inventory_hostname == "multichain1"

- include: multichain-configureServices.yml