---

- debug: msg="Installing MultiChain"

- name: Install libselinux-python
  yum: name=libselinux-python

- name: Creates directory
  file: path=~/.ssh state=directory mode=0600

- name: Copy ssh keys - i know this is badddd
  copy: src={{ item }} dest=~/.ssh/{{ item }} mode=0600
  with_items:
    - id_rsa
    - id_rsa.pub

- name: Set up authorized_keys for the root user
  authorized_key: user=root key="{{ item }}"
  with_file:
    - id_rsa.pub

- name: Set up authorized_keys for the root user
  authorized_key: user=vagrant key="{{ item }}"
  with_file:
    - id_rsa.pub

- name: download {{ multichain_url }}
  get_url: url="{{ multichain_url }}"
           dest="/tmp/{{ multichain_file }}"

- name: unarchive {{ multichain_file }} into /usr/local/bin
  unarchive: src=/tmp/{{ multichain_file }}
             dest={{ multichain_usr_parent_dir }}
             remote_src=yes
             copy=no
             creates="{{ multichain_usr_parent_dir }}/multichain-{{ multichain_version }}"

- name: Setup multichain distribution symlinks
  file: src="{{ item.src }}"
        dest="{{ item.dest }}"
        state=link
  with_items:
    - { src: "{{ multichain_usr_parent_dir }}/multichain-{{ multichain_version }}", dest: "{{ multichain_usr_dir }}" }

- name: Add path to profile (only if CentOS or RHEL)
  template: src=etc/profile.d/multichain.sh.j2
            dest="/etc/profile.d/multichain.sh"
            mode=0644
  when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux')
